"""Request-scoped localization helpers for the Agent Mail web interface."""

# Chinese translations intentionally use full-width Chinese punctuation.
# ruff: noqa: RUF001

from __future__ import annotations

from contextvars import ContextVar, Token

SUPPORTED_INTERFACE_LOCALES = ("en", "zh-CN")
DEFAULT_INTERFACE_LOCALE = "en"
INTERFACE_LOCALE_COOKIE = "agent_mail_locale"

_current_interface_locale: ContextVar[str] = ContextVar(
    "current_interface_locale",
    default=DEFAULT_INTERFACE_LOCALE,
)


# English source strings intentionally act as stable message identifiers. This
# keeps templates readable and gives untranslated strings a safe English
# fallback while the catalog grows.
_ZH_CN: dict[str, str] = {
    "Agent Mail": "智能体邮件",
    "Skip to main content": "跳到主要内容",
    "English": "English",
    "简体中文": "简体中文",
    "Interface language": "界面语言",
    "Switch to English": "切换到 English",
    "Switch to Simplified Chinese": "切换到简体中文",
    "Show interactive tutorial": "打开交互式教程",
    "Show help": "显示帮助",
    "Toggle dark/light mode": "切换深色/浅色模式",
    "Toggle dark mode": "切换深色模式",
    "Notifications": "通知",
    "Close notification": "关闭通知",
    "Projects": "项目",
    "Project": "项目",
    "Agents": "智能体",
    "Agent": "智能体",
    "Messages": "消息",
    "Message": "消息",
    "Inbox": "收件箱",
    "Unified Inbox": "统一收件箱",
    "Search": "搜索",
    "Archive": "归档",
    "Attachments": "附件",
    "File Reservations": "文件预留",
    "Claims": "声明",
    "Thread": "会话",
    "Activity": "活动",
    "Timeline": "时间线",
    "Network": "关系网络",
    "Time Travel": "历史回溯",
    "Commit": "提交",
    "Guide": "指南",
    "Refresh": "刷新",
    "Close": "关闭",
    "Cancel": "取消",
    "Copy": "复制",
    "Copied": "已复制",
    "Copy to clipboard": "复制到剪贴板",
    "Open": "打开",
    "Download": "下载",
    "View": "查看",
    "Back": "返回",
    "Previous": "上一个",
    "Next": "下一个",
    "Loading...": "正在加载…",
    "No results": "没有结果",
    "No data": "暂无数据",
    "Unknown": "未知",
    "Active": "活跃",
    "Expired": "已过期",
    "All": "全部",
    "Unread": "未读",
    "Read": "已读",
    "Urgent": "紧急",
    "High": "高",
    "Normal": "普通",
    "Low": "低",
    "Subject": "主题",
    "Sender": "发件人",
    "Recipients": "收件人",
    "Date": "日期",
    "Status": "状态",
    "Priority": "优先级",
    "Type": "类型",
    "Name": "名称",
    "Path": "路径",
    "Reason": "原因",
    "Created": "创建时间",
    "Updated": "更新时间",
    "Expires": "过期时间",
    "Yes": "是",
    "No": "否",
    "Reply": "回复",
    "Forward": "转发",
    "Mark as read": "标记为已读",
    "Keyboard Shortcuts": "键盘快捷键",
    "Work faster with keyboard navigation": "使用键盘导航提升操作效率",
    "Command palette": "命令面板",
    "This help panel": "此帮助面板",
    "Focus search": "聚焦搜索框",
    "Go to projects": "前往项目列表",
    "Next item": "下一项",
    "Previous item": "上一项",
    "Open item": "打开项目",
    "Go back": "返回",
    "Search commands, navigate, or type '?' for help...": "搜索命令、快速导航，或输入“?”查看帮助…",
    "Command palette search": "命令面板搜索",
    "No commands found. Try different keywords.": "未找到命令，请尝试其他关键词。",
    "Navigate": "导航",
    "Select": "选择",
    "Error": "错误",
    "Oops! Something went wrong": "糟糕，出现了问题",
    "We're sorry for the inconvenience. Try one of the options below or contact support if the problem persists.": "很抱歉给你带来不便。请尝试以下操作；如果问题仍然存在，请联系支持人员。",
    "Go Back": "返回",
    "Go Home": "返回首页",
    "Retry": "重试",
    "If this error persists, try going back or returning to the home page": "如果错误持续出现，请尝试返回上一页或回到首页",
    "Documentation": "文档",
    "Report Issue": "报告问题",
    "Multi-Agent Collaboration Platform": "多智能体协作平台",
    "Your": "你的",
    "Orchestrate, coordinate, and empower AI agents to collaborate seamlessly": "编排、协调并赋能 AI 智能体，让协作顺畅高效",
    "Quick search across all projects": "快速搜索所有项目",
    "Learn how Agent Mail works": "了解智能体邮件的工作方式",
    "Take a Tour": "开始导览",
    "Total Projects": "项目总数",
    "Currently active": "当前活跃",
    "Active Agents": "活跃智能体",
    "Total Messages": "消息总数",
    "Metrics coming soon": "指标即将推出",
    "Active Projects": "活跃项目",
    "{active} active, {archived} archived": "{active} 个活跃，{archived} 个已归档",
    "Filter projects...": "筛选项目…",
    "Filter projects": "筛选项目",
    "Grid view": "网格视图",
    "List view": "列表视图",
    "Related Projects": "关联项目",
    "Why Link Projects?": "为什么要关联项目？",
    "Confirming related projects helps agents discover relevant context across your workspace.": "确认项目关联后，智能体可以在整个工作区中发现相关上下文。",
    "When projects are linked, agents can:": "关联项目后，智能体可以：",
    "Find dependencies:": "发现依赖：",
    "Discover related code and shared components": "发现相关代码和共享组件",
    "Coordinate work:": "协调工作：",
    "Connect with agents working on related systems": "与处理相关系统的智能体建立联系",
    "Maintain consistency:": "保持一致：",
    "Keep shared patterns and conventions aligned": "统一共享模式和约定",
    "Suggested sibling project": "建议关联的同级项目",
    "Confirm Link": "确认关联",
    "Dismiss": "忽略",
    "Undo": "撤销",
    "No matching projects": "没有匹配的项目",
    "No project names or slugs match your search query. Try different keywords or clear the search to see all projects.": "没有项目名称或标识与搜索条件匹配。请尝试其他关键词，或清除搜索以查看全部项目。",
    "Clear search": "清除搜索",
    "Archived": "已归档",
    "View archived project": "查看已归档项目",
    "Ready to get started?": "准备好开始了吗？",
    "Create your first project to enable seamless multi-agent collaboration and coordination.": "创建第一个项目，开启顺畅的多智能体协作与协调。",
    "Agent Messaging": "智能体消息",
    "Enable agents to communicate and share context": "让智能体能够沟通并共享上下文",
    "Signal editing intent to coordinate between agents": "通过声明编辑意图来协调智能体之间的工作",
    "Full History": "完整历史",
    "Track all interactions with Git-backed storage": "通过 Git 支持的存储追踪所有交互",
    "Create Your First Project": "创建第一个项目",
    "Coming Soon": "即将推出",
    "Coming soon - Create projects through the UI": "即将支持通过界面创建项目",
    "Human Overseer": "人工监督者",
    "Send high-priority message as Human Overseer": "以人工监督者身份发送高优先级消息",
    "Reservations": "预留",
    "View file coordination signals": "查看文件协调信号",
    "View shared files": "查看共享文件",
    "Restore Project": "恢复项目",
    "Archive Project": "归档项目",
    "Archive Project?": "要归档项目吗？",
    "This action can be undone later": "稍后可以撤销此操作",
    "Archiving hides the project from the main project list. All messages, agents, and history remain intact.": "归档后，该项目会从主项目列表中隐藏；所有消息、智能体和历史记录都会完整保留。",
    "Archiving": "归档",
    "will hide it from active project lists.": "后，该项目将从活跃项目列表中隐藏。",
    "All messages will be preserved and the project can be restored at any time.": "所有消息都会保留，并且可以随时恢复此项目。",
    "Search Messages": "搜索消息",
    "Scan subjects and bodies from every message in this project.": "搜索此项目中每条消息的主题和正文。",
    "By default we match both subject and body text. Add filters below to narrow the scope or change how results are ranked.": "默认同时匹配主题和正文。可使用下方筛选条件缩小范围或调整结果排序方式。",
    "Example:": "示例：",
    "Tip: searches are case-insensitive and support phrases in quotes, e.g.": "提示：搜索不区分大小写，并支持用引号包围短语，例如",
    "Search by subject, body, or use filters like subject:keyword...": "搜索主题、正文，或使用 subject:关键词 等筛选条件…",
    "Search project messages": "搜索项目消息",
    "Toggle advanced search filters": "显示或隐藏高级搜索筛选条件",
    "Limit matching to the subject line or body when you need a tighter query.": "需要更精确的查询时，可将匹配范围限制在主题或正文。",
    "Switch to chronological sorting when you need the latest updates at the top.": "需要将最新更新置顶时，请切换为按时间排序。",
    "Subject prioritization nudges messages whose subject matches your query higher without hiding relevant body matches.": "主题优先会提升主题匹配消息的排序，同时保留相关的正文匹配结果。",
    "Canonical thread identifier shared across agents": "智能体之间共享的标准会话标识符",
    "No matching messages": "没有匹配的消息",
    "No messages in this project match your search criteria. Try using different keywords, checking for typos, or broadening your search terms.": "此项目中没有符合搜索条件的消息。请尝试其他关键词、检查拼写，或扩大搜索范围。",
    "Registered Agents": "已注册智能体",
    "Active collaborators in this project": "此项目中的活跃协作者",
    "Copy agent name": "复制智能体名称",
    "Retire agent": "停用智能体",
    "Retired": "已停用",
    "View Inbox": "查看收件箱",
    "Restore agent to active": "将智能体恢复为活跃状态",
    "No agents registered yet": "尚未注册智能体",
    "Use": "使用",
    "to add agents": "来添加智能体",
    "Agents will appear here once they register with this project using the MCP tools.": "智能体通过 MCP 工具注册到此项目后，将显示在这里。",
    "unread": "未读",
    "Refresh inbox": "刷新收件箱",
    "Mark Read": "标记已读",
    "Mark selected as read": "将所选消息标记为已读",
    "Mark selected messages as read": "将所选消息标记为已读",
    "Delete": "删除",
    "Permanently delete selected messages": "永久删除所选消息",
    "Delete selected messages": "删除所选消息",
    "Clear selection": "清除选择",
    "Mark All Read": "全部标记为已读",
    "Mark all messages as read": "将所有消息标记为已读",
    "Search messages...": "搜索消息…",
    "Search messages": "搜索消息",
    "Needs ack": "待确认",
    "Sort": "排序",
    "Newest First": "最新优先",
    "Oldest First": "最早优先",
    "By Subject": "按主题",
    "By Sender": "按发件人",
    "Select message:": "选择消息：",
    "ack_required is set on this message and you have not acknowledged it yet": "此消息要求确认，而你尚未确认",
    "Acknowledged": "已确认",
    "Inbox is empty": "收件箱为空",
    "No messages match your current search or filter criteria. Try broadening your search terms or clearing the active filters to see all messages.": "没有消息符合当前搜索或筛选条件。请尝试扩大搜索范围，或清除当前筛选条件以查看所有消息。",
    "Messages sent to": "发送给",
    "will appear here automatically. Messages are typically delivered by other agents, external systems, or API integrations configured for this project.": "的消息会自动显示在这里。这些消息通常由其他智能体、外部系统或为此项目配置的 API 集成发送。",
    "Soon": "即将推出",
    "Coming soon - Reply to this message": "即将支持回复此消息",
    "Coming soon - Forward this message": "即将支持转发此消息",
    "High Priority": "高优先级",
    "Low Priority": "低优先级",
    "View Thread": "查看会话",
    "View commit in archive": "在归档中查看提交",
    "From": "发件人",
    "To": "收件人",
    "Read at": "读取时间",
    "Acked at": "确认时间",
    "No file": "无文件",
    "Part of a Conversation Thread": "属于一个对话会话",
    "View Full Thread": "查看完整会话",
    "Other messages in this thread:": "此会话中的其他消息：",
    "No subject": "无主题",
    "Thread Conversation": "会话对话",
    "No content": "无内容",
    "End of conversation": "对话结束",
    "Back to Project": "返回项目",
    "View Full Message": "查看完整消息",
    "Find messages across the project": "在整个项目中查找消息",
    "Query Help": "查询帮助",
    "Query Syntax": "查询语法",
    "Field filters:": "字段筛选：",
    "Combine terms:": "组合条件：",
    "Wildcard:": "通配符：",
    "Search in:": "搜索范围：",
    "Both": "主题和正文",
    "Body": "正文",
    "Order by:": "排序方式：",
    "Relevance": "相关性",
    "Time": "时间",
    "Boost subject": "主题优先",
    "Tokens:": "查询标记：",
    "Add token:": "添加标记：",
    "Add": "添加",
    "Results": "结果",
    "View message": "查看消息",
    "Remove token": "移除标记",
    "Token field type": "标记字段类型",
    "keyword or phrase": "关键词或短语",
    "No results found": "未找到结果",
    "No messages match your search query. Try different keywords or use the query help above.": "没有消息符合搜索条件。请尝试其他关键词，或使用上方的查询帮助。",
    "Clear Search": "清除搜索",
    "Advisory system:": "提示性系统：",
    "Reservations are": "预留是",
    "signals": "协作信号",
    "Agents can still edit files, but they'll see warnings if conflicts exist.": "智能体仍然可以编辑文件，但发生冲突时会收到警告。",
    "ID": "ID",
    "Path Pattern": "路径模式",
    "Exclusive": "独占",
    "Shared": "共享",
    "Released": "已释放",
    "No Active Reservations": "没有活跃的文件预留",
    "File reservations help agents coordinate who's working on what files to avoid conflicts.": "文件预留可以帮助智能体协调各自正在处理的文件，从而避免冲突。",
    "How File Reservations Work": "文件预留如何工作",
    "Agent reserves a file": "智能体预留文件",
    "Other agents see the reservation": "其他智能体看到该预留",
    "Reservation expires or is released": "预留过期或被释放",
    "Important:": "重要：",
    "File reservations are": "文件预留仅用于",
    "advisory only": "提示协作",
    "and block conflicting commits, install the optional pre-commit hook in your code repository.": "并阻止存在冲突的提交，请在代码仓库中安装可选的 pre-commit 钩子。",
    "not hard locks.": "而不是强制文件锁。",
    "They're signals to help coordination, not hard locks. To": "它们是帮助协调的信号，而不是强制锁。若要",
    "enforce": "强制执行",
    "Messages with attached files": "包含附件的消息",
    "View Message": "查看消息",
    "No attachments found": "未找到附件",
    "Messages with attachments will appear here.": "带附件的消息将显示在这里。",
    "Search all messages across all projects and agents...": "搜索所有项目和智能体的消息…",
    "Search all messages": "搜索所有消息",
    "Filters": "筛选",
    "Split view (Gmail style)": "分栏视图（Gmail 风格）",
    "List view only": "仅列表视图",
    "Exit fullscreen": "退出全屏",
    "Enter fullscreen": "进入全屏",
    "Auto-refresh": "自动刷新",
    "Toggle automatic refresh": "切换自动刷新",
    "All Projects": "所有项目",
    "All Senders": "所有发件人",
    "Recipient": "收件人",
    "All Recipients": "所有收件人",
    "Importance": "重要程度",
    "Threads": "会话",
    "All Messages": "所有消息",
    "Threaded Only": "仅会话消息",
    "Non-threaded": "非会话消息",
    "Clear": "清除",
    "Select all messages": "选择所有消息",
    "Longest First": "最长优先",
    "Your unified inbox is empty": "统一收件箱为空",
    "No messages match your current search query or filter criteria. Try broadening your search terms or clearing the active filters to see all messages.": "没有消息符合当前搜索或筛选条件。请尝试扩大搜索范围，或清除当前筛选条件以查看所有消息。",
    "Messages from all your AI agents across all projects will appear here automatically when they're received. This unified view helps you stay on top of all agent communications in one place.": "所有项目中各 AI 智能体发来的消息会在收到后自动显示于此。统一视图让你可以在一个位置掌握全部智能体通信。",
    "Clear All Filters": "清除所有筛选条件",
    "Sent": "发送时间",
    "Copy Link": "复制链接",
    "Open in Project": "在项目中打开",
    "Message Content": "消息内容",
    "Select a message to view": "请选择一条消息",
    "Choose a message from the list to see its full contents and details": "从列表中选择一条消息，查看完整内容和详细信息",
    "Next message": "下一条消息",
    "Previous message": "上一条消息",
    "Deselect": "取消选择",
    "Your Projects": "你的项目",
    "View details": "查看详情",
    "No projects found": "未找到项目",
    "No project names match your search query": "没有项目名称符合搜索条件",
    "No Projects Yet": "还没有项目",
    "Create your first project to get started with agent collaboration": "创建第一个项目，开始智能体协作",
    "Send Message as Human Overseer": "以人工监督者身份发送消息",
    "Send high-priority instructions directly to your agents. Messages are automatically marked as urgent.": "直接向智能体发送高优先级指令。消息会自动标记为紧急。",
    "How Human Overseer messages work": "人工监督者消息的工作方式",
    "Agents receive your message with a preamble indicating human guidance. They'll pause current work to prioritize your request, then resume their original tasks.": "智能体收到消息时，会看到表明这是人工指导的前言。它们会暂停当前工作、优先处理你的请求，然后恢复原有任务。",
    "Select which agents should receive this message": "选择要接收此消息的智能体",
    "Select All": "全选",
    "Search agents...": "搜索智能体…",
    "Search agents": "搜索智能体",
    "No matching agents": "没有匹配的智能体",
    "No agent names match your search query": "没有智能体名称符合搜索条件",
    "No Agents Registered": "尚未注册智能体",
    "No agents are currently registered in this project.": "此项目目前没有已注册的智能体。",
    "Compose your message in GitHub-flavored Markdown": "使用 GitHub 风格 Markdown 编写消息",
    "Write": "编辑",
    "Preview": "预览",
    "Split": "分栏",
    "required": "必填",
    "Bold": "粗体",
    "Insert bold text": "插入粗体文本",
    "Italic": "斜体",
    "Insert italic text": "插入斜体文本",
    "Code": "代码",
    "Insert inline code": "插入行内代码",
    "Heading": "标题",
    "Insert heading": "插入标题",
    "List": "列表",
    "Insert list": "插入列表",
    "Link": "链接",
    "Insert link": "插入链接",
    "Code Block": "代码块",
    "Insert code block": "插入代码块",
    "e.g., Urgent: Review security vulnerability": "例如：紧急：审查安全漏洞",
    "e.g., 42 or custom-thread-id": "例如：42 或 custom-thread-id",
    "Leave blank to start a new conversation": "留空以开始新会话",
    "Send Message": "发送消息",
    "Confirm Send": "确认发送",
    "Review your message before sending": "发送前请检查消息内容",
    "Recipients:": "收件人：",
    "Subject:": "主题：",
    "Priority:": "优先级：",
    "Error rendering markdown preview": "Markdown 预览渲染失败",
    "Sending...": "正在发送…",
    "Send to": "发送给",
    "agent": "个智能体",
    "agents": "个智能体",
    "Agents will pause their current work to address this message.": "智能体将暂停当前工作以处理此消息。",
    "Confirm & Send": "确认并发送",
    "Activity Feed": "活动动态",
    "Recent commits across all projects": "所有项目的近期提交",
    "Commits": "提交数",
    "Insertions": "新增行",
    "Deletions": "删除行",
    "Authors": "作者",
    "No commits yet": "暂无提交",
    "Archive Browser": "归档浏览器",
    "Browser": "浏览器",
    "Navigate and explore Git archive structure": "导航并探索 Git 归档结构",
    "Select a file to view its contents": "选择文件以查看内容",
    "Directory selected - click a file to view its contents": "已选择目录——点击文件查看内容",
    "Files Changed": "变更文件数",
    "No diff available for this commit": "此提交没有可用的差异内容",
    "Archive Guide": "归档指南",
    "Network Graph": "关系网络图",
    "View historical snapshots of agent inboxes": "查看智能体收件箱的历史快照",
    "Communication Timeline": "通信时间线",
    "Generating timeline...": "正在生成时间线…",
    "Error rendering timeline": "时间线渲染失败",
    "Agent Communication Network": "智能体通信网络",
    "Interactive visualization for": "交互式可视化：",
    "Agent node": "智能体节点",
    "Message flow": "消息流",
    "Size = total messages": "大小 = 消息总数",
    "Select project...": "选择项目…",
    "Date & Time": "日期和时间",
    "Historical Snapshot": "历史快照",
    "inbox as of": "收件箱快照时间：",
    "Inbox was empty at this time": "该时间点的收件箱为空",
    "No messages existed in this agent's inbox at the selected timestamp. Messages may have been received later or already processed before this point.": "在所选时间点，此智能体的收件箱中没有消息。消息可能在之后才收到，或在此之前已经处理完毕。",
    "Visual message flow for": "消息流可视化：",
}


def normalize_interface_locale(value: str | None) -> str | None:
    """Return a supported locale for a user-provided locale token."""

    if not value:
        return None
    candidate = value.strip().replace("_", "-").lower()
    if candidate == "en" or candidate.startswith("en-"):
        return "en"
    if candidate == "zh" or candidate.startswith("zh-"):
        return "zh-CN"
    return None


def select_interface_locale(
    *,
    query_locale: str | None,
    cookie_locale: str | None,
    accept_language: str | None,
) -> str:
    """Select a locale using explicit query, persisted choice, then browser preference."""

    explicit = normalize_interface_locale(query_locale)
    if explicit is not None:
        return explicit

    persisted = normalize_interface_locale(cookie_locale)
    if persisted is not None:
        return persisted

    if accept_language:
        language_ranges: list[tuple[float, int, str]] = []
        for index, item in enumerate(accept_language.split(",")):
            language, *parameters = item.strip().split(";")
            quality = 1.0
            for parameter in parameters:
                key, separator, value = parameter.strip().partition("=")
                if separator and key.lower() == "q":
                    try:
                        quality = float(value)
                    except ValueError:
                        quality = 0.0
            normalized = normalize_interface_locale(language)
            if normalized is not None and quality > 0:
                language_ranges.append((quality, -index, normalized))
        if language_ranges:
            return max(language_ranges)[2]

    return DEFAULT_INTERFACE_LOCALE


def set_interface_locale(locale: str) -> Token[str]:
    """Set the request-local interface language and return its reset token."""

    normalized = normalize_interface_locale(locale) or DEFAULT_INTERFACE_LOCALE
    return _current_interface_locale.set(normalized)


def reset_interface_locale(token: Token[str]) -> None:
    """Restore the interface locale that preceded ``set_interface_locale``."""

    _current_interface_locale.reset(token)


def get_interface_locale() -> str:
    """Return the interface locale active for the current request."""

    return _current_interface_locale.get()


def gettext(message: str) -> str:
    """Translate an English UI message into the active interface language."""

    if get_interface_locale() == "zh-CN":
        return _ZH_CN.get(message, message)
    return message
